model_name: "biovid_marlin_multiclass_lp"
backbone: "marlin_vit_base_ytf"
dataset: "biovid"
task: "multiclass"
temporal_reduction: "mean"
learning_rate: 1.0e-5
seq_mean_pool: true
finetune: false
num_classes: 5