# config/multitask_coral_template.yaml

# --- Required --- 
model_name: multitask_pain_stimulus_run_05  # Name for checkpoints and logs

num_pain_classes: 5  # Number of ordinal pain levels (Syracuse)
num_stimulus_classes: 5  # Number of ordinal stimulus levels (BioVid)

# Feature directory names (relative to the respective data paths provided via CLI)
syracuse_feature_dir: multimodal_marlin_base # Example: Feature directory for Syracuse
biovid_feature_dir: multimodal_marlin_base   # Example: Feature directory for BioVid (can be the same or different)
shoulder_pain_feature_dir: "multimodal_marlin_base" # Example: Feature directory for Shoulder Pain
 
temporal_reduction: mean  # How to aggregate features temporally (mean, max, min, none)

learning_rate: 1.0e-5      # Learning rate for the optimizer

# --- Optional: Model & Loss Weights --- 
pain_loss_weight: 1.0  # Weight for the pain task loss in the combined loss
stim_loss_weight: 0.5  # Weight for the stimulus task loss in the combined loss

use_stim_weight_scheduler: true
initial_stim_weight: 50.0
final_stim_weight: 0.5  
stim_weight_decay_epochs: 150
stim_weight_sched_type: "cosine"

# --- Optional: Class Imbalance Handling ---
use_class_weights: true  # Whether to use inverse frequency class weighting to handle class imbalance
balance_pain_classes: true  # Whether to use weighted sampling to balance pain classes in dataloaders (only affects Syracuse data)

# Optional: Define hidden layers for the shared MLP encoder
# If null or empty, a single Linear layer is used.
encoder_hidden_dims: [512,256,128] # Example: [hidden1_size, hidden2_size]
# encoder_hidden_dims: null

# --- Optional: Data Balancing --- 
balance_sources: false           # Set to true to sample BioVid to match Syracuse training set size
balance_stimulus_classes: false # Set to true to apply class balancing within the BioVid training samples

# --- Optional: Add other parameters if needed by model/datamodule ---
# Example: optimizer_name: AdamW (if you add this option to the model) 

# Example config with label smoothing
label_smoothing: 0.05  # Typical values are 0.05 to 0.2 
use_distance_penalty: true
focal_gamma: 2.0  # Focal loss parameter (default is 2.0)
patience: 150  # Number of epochs to wait before stopping training if no improvement
