# New hyperparameters for coral_loss
label_smoothing: 0.0  # Default to 0.0 for no label smoothing
use_distance_penalty: false  # Default to false to disable distance penalty
focal_gamma: null  # Default to null to disable focal weighting

# Early stopping configuration
patience: 200  # Early stopping patience (epochs)

# Existing configuration keys
model_name: multitask_coral_run
num_pain_classes: 5
num_stimulus_classes: 5
syracuse_feature_dir: syracuse_features
biovid_feature_dir: biovid_features
shoulder_pain_feature_dir: null  # Optional: feature directory for ShoulderPain dataset, set to null to disable
temporal_reduction: mean
learning_rate: 0.001
weight_decay: 0.0
use_class_weights: false
balance_pain_classes: false
pain_loss_weight: 1.0
stim_loss_weight: 1.0
balance_sources: false
balance_stimulus_classes: false
encoder_hidden_dims: [256, 128] 